# Auto generated by PSDB due to incorrect execution
# Read the Docs on how to properly use PSDB
import pythondatabase, time
pythondatabase.settings(True, True, True, True)
pythondatabase.start()
